name: Flutter Build & Deploy

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to build'
        required: true
        default: 'both'
        type: choice
        options:
          - android
          - ios
          - both
      bump_build: 
        description: 'Increase build number'
        required: false
        type: boolean
        default: true

  release:
    types: [published]

permissions:
  contents: write

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      platforms: ${{ steps.platforms.outputs.platforms }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Determine platforms
        id: platforms
        run: |
          if [[ "${{ github.event_name }}" == "release" || "${{ github.event.inputs.platform }}" == "both" ]]; then
            echo 'platforms=["android", "ios"]' >> $GITHUB_OUTPUT
          else
            echo 'platforms=["${{ github.event.inputs.platform }}"]' >> $GITHUB_OUTPUT
          fi

      - name: Calculate Version and Build Number
        id: version
        run: |
          VERSION=$(grep "^version:" pubspec.yaml | cut -d' ' -f2)

          # Determine build number
          BUILD=$(echo "$VERSION" | cut -d'+' -f2)
          if [[ "${{ github.event_name }}" != "release"  && "${{ github.event.inputs.bump_build }}" == "true" ]]; then
            BUILD=$((BUILD + 1))
          fi
          echo "build_number=$BUILD" >> $GITHUB_OUTPUT
          
          # Determine version name
          if [[ "${{ github.event_name }}" == "release" ]]; then
            # Strip 'v' from tag (e.g., v1.2.3 -> 1.2.3)
            VERSION=$(echo "${{ github.event.release.tag_name }}" | sed 's/^v//')
          else
            # Get current version from pubspec
            VERSION=$(echo "$VERSION" | cut -d'+' -f1)
          fi
          echo "version_name=$VERSION" >> $GITHUB_OUTPUT
      
      - name: Generate Changelog
        if: github.event_name == 'release'
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changes
        run: |
          # Update pubspec.yaml
          VERSION="${{ steps.version.outputs.version_name }}"
          BUILD="${{ steps.version.outputs.build_number }}"
          sed -i "s/^version: .*/version: $VERSION+$BUILD/" pubspec.yaml

          # Update CHANGELOG.md
          echo "${{ steps.changelog.outputs.changelog }}" > CHANGELOG.md
          
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add pubspec.yaml CHANGELOG.md
          if git diff-index --quiet HEAD --; then
              echo "No changes to commit."
          else
              git commit -m "chore(release): v$VERSION+$BUILD [skip ci]"
          fi
          git push origin HEAD:main

      - name: Update Release details
        if: github.event_name == 'release'
        run: |
          gh release edit ${{ github.event.release.tag_name }} --notes "${{ steps.changelog.outputs.changelog }}"
          # Retag
          git tag -d ${{ github.event.release.tag_name }} || true
          git tag ${{ github.event.release.tag_name }}
          git push origin ${{ github.event.release.tag_name }} --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  deploy:
    needs: prepare
    strategy:
      fail-fast: false
      matrix:
        platform: ${{ fromJson(needs.prepare.outputs.platforms) }}

    runs-on: ${{ (matrix.platform == 'ios') && 'macos-latest' || 'ubuntu-latest' }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          ref: main
    
      - name: Fetch material_plus dependency
        run: git clone --depth=1 https://gitlab.com/flutterby-group/material_plus.git ../material_plus
      
      - name: Write keys.dart to file
        run: |
          cat << EOF > ./lib/keys.dart
          ${{ secrets.KEYS_FILE }}
          EOF
      
      - name: Decode Android files
        if: matrix.platform == 'android'
        run: |
          echo "${{ secrets.ANDROID_UPLOAD_KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks
          echo "${{ secrets.ANDROID_KEY_PROPERTIES }}" > android/key.properties
          echo "${{ secrets.ANDROID_SERVICE_ACCOUNT_JSON_BASE64 }}" | base64 --decode > ../musbx-service-account-key.json

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      
      - name: Install Ruby & Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true

      - name: Run Fastlane
        working-directory: ${{matrix.platform}}
        env:
          CI: true # Tell Fastlane we are in a CI

          KEYSTORE_PASSWORD: ${{ secrets.ANDROID_UPLOAD_KEYSTORE_PASSWORD }} # Password for keystore (Android only)

          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }} # Password for fastlane match (iOS only)
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION_BASE64 }} # Git authorization for fastlane match (iOS only)
          
          APPSTORE_CONNECT_API_ISSUER_ID: ${{ secrets.APPSTORE_CONNECT_API_ISSUER_ID }} # Appstore Connect API issuer ID (iOS only)
          APPSTORE_CONNECT_API_KEY_ID: ${{ secrets.APPSTORE_CONNECT_API_KEY_ID }} # Appstore Connect API key ID (iOS only)
          APPSTORE_CONNECT_API_KEY_CONTENT: ${{ secrets.APPSTORE_CONNECT_API_KEY_CONTENT_BASE64 }} # Content of the Appstore Connect API key (iOS only)

        run: |
          bundle install
          bundle exec fastlane beta

      - name: Upload Artifacts to Release
        if: github.event_name == 'release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "${{ matrix.platform }}" == "android" ]; then
            gh release upload ${{ github.event.release.tag_name }} build/app/outputs/bundle/release/app-release.aab
          else
            gh release upload ${{ github.event.release.tag_name }} ios/build/Runner.ipa
          fi
